// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyuugweuggzzfcwsvdie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5dXVnd2V1Z2d6emZjd3N2ZGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjI5MTgsImV4cCI6MjA2NDI5ODkxOH0.mIq94qAerLy0Zwqb45wZy79FS6oaZdwF_8JE9H9Pt1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);